-- MySQL Script generated by MySQL Workbench
-- mié 11 may 2022 18:35:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema plataformaexamenes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plataformaexamenes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plataformaexamenes` DEFAULT CHARACTER SET utf8mb4 ;
USE `plataformaexamenes` ;

-- -----------------------------------------------------
-- Table `plataformaexamenes`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`grado` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`asignatura` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `curso` INT(11) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `id_grado` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKa0jdgb99wks5ow8nr45ormu7m` (`id_grado` ASC) VISIBLE,
  CONSTRAINT `FKa0jdgb99wks5ow8nr45ormu7m`
    FOREIGN KEY (`id_grado`)
    REFERENCES `plataformaexamenes`.`grado` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`usuario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_5171l57faosmj8myawaucatdw` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_863n1y3x0jalatoir4325ehal` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`examen` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `aciertos` BIT(1) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `respuesta` BIT(1) NOT NULL,
  `id_asignatura` BIGINT(20) NULL DEFAULT NULL,
  `id_usuario` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKqq57kbxu6jbrrewxti6ttwj9k` (`id_asignatura` ASC) VISIBLE,
  INDEX `FK1u52492jgrdp4m3iphfr0skpt` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK1u52492jgrdp4m3iphfr0skpt`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `plataformaexamenes`.`usuario` (`id`),
  CONSTRAINT `FKqq57kbxu6jbrrewxti6ttwj9k`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `plataformaexamenes`.`asignatura` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`matricularse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`matricularse` (
  `num_alumnos` INT(11) NOT NULL,
  `id_usuario` BIGINT(20) NOT NULL,
  `id_asignatura` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_asignatura`),
  INDEX `FKelu6camvy5mds8uktri53ia7o` (`id_asignatura` ASC) VISIBLE,
  CONSTRAINT `FKelu6camvy5mds8uktri53ia7o`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `plataformaexamenes`.`asignatura` (`id`),
  CONSTRAINT `FKnscj5dstbjulk8x9df0u350bj`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `plataformaexamenes`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`pregunta` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `num_pregunta` INT(11) NOT NULL,
  `preguntas` VARCHAR(255) NOT NULL,
  `respuestas` BIT(1) NOT NULL,
  `id_examen` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKr5h0q267ur6wgli5kkjopx4sh` (`id_examen` ASC) VISIBLE,
  CONSTRAINT `FKr5h0q267ur6wgli5kkjopx4sh`
    FOREIGN KEY (`id_examen`)
    REFERENCES `plataformaexamenes`.`examen` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
