-- MySQL Script generated by MySQL Workbench
-- mar 26 abr 2022 17:13:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema plataformaexamenes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plataformaexamenes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plataformaexamenes` DEFAULT CHARACTER SET utf8mb4 ;
USE `plataformaexamenes` ;

-- -----------------------------------------------------
-- Table `plataformaexamenes`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`grado` (
  `id` BIGINT(30) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `departamento` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`asignatura` (
  `id` BIGINT(30) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `num_curso` TINYINT(3) NOT NULL,
  `id_grado` BIGINT(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_grado_UNIQUE` (`id_grado` ASC) VISIBLE,
  INDEX `id_grado_idx` (`id_grado` ASC) VISIBLE,
  CONSTRAINT `id_gradofk`
    FOREIGN KEY (`id_grado`)
    REFERENCES `plataformaexamenes`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`user` (
  `id` BIGINT(30) NOT NULL,
  `username` VARCHAR(245) NOT NULL,
  `email` VARCHAR(245) NOT NULL,
  `password` VARCHAR(245) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `nombre` VARCHAR(245) NOT NULL,
  `apellidos` VARCHAR(245) NOT NULL,
  `rol` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`examen` (
  `id` BIGINT(30) NOT NULL AUTO_INCREMENT,
  `respuesta` TINYINT(4) NOT NULL,
  `aciertos` TINYINT(4) NOT NULL,
  `nota` DECIMAL(10,0) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `id_asignatura` BIGINT(30) NULL DEFAULT NULL,
  `id_usuario` BIGINT(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_asignatura_UNIQUE` (`id_asignatura` ASC) VISIBLE,
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_asignaturafk`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `plataformaexamenes`.`asignatura` (`id`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `plataformaexamenes`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`matricularse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`matricularse` (
  `id_usuario` BIGINT(30) NOT NULL,
  `id_asignatura` BIGINT(30) NOT NULL,
  `num_alumnos` INT(60) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_asignatura`),
  INDEX `fk_matricularse_1_idx` (`id_asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_matricularse_asignatura1`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `plataformaexamenes`.`asignatura` (`id`),
  CONSTRAINT `fk_matricularse_user1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `plataformaexamenes`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataformaexamenes`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaexamenes`.`pregunta` (
  `id_preguntas` BIGINT(30) NOT NULL AUTO_INCREMENT,
  `preguntas` VARCHAR(245) NOT NULL,
  `num_pregunta` INT(10) NOT NULL,
  `respuestas` VARCHAR(245) NOT NULL,
  `id_examen` BIGINT(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_preguntas`),
  UNIQUE INDEX `id_examen_UNIQUE` (`id_examen` ASC) VISIBLE,
  CONSTRAINT `id_examenfk`
    FOREIGN KEY (`id_examen`)
    REFERENCES `plataformaexamenes`.`examen` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
